# Generated by Django 6.0.2 on 2026-02-23 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, help_text='Father, Mother, Guardian, Caregiver etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(limit_choices_to={'role': 'family'}, on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='patients.patientprofile')),
            ],
            options={
                'unique_together': {('family_member', 'patient')},
            },
        ),
    ]
