# Generated by Django 6.0.2 on 2026-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_familypatientlink_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familypatientlink',
            name='can_manage_appointments',
            field=models.BooleanField(default=False),
        ),
    ]
