# Generated by Django 6.0.2 on 2026-02-24 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_doctor_notes_appointment_follow_up_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by_family',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'family'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created_for_family', to=settings.AUTH_USER_MODEL),
        ),
    ]
