# Generated by Django 6.0.2 on 2026-02-11 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(limit_choices_to={'role': 'family'}, on_delete=django.db.models.deletion.CASCADE, related_name='family_monitoring', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitored_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('family_member', 'patient')},
            },
        ),
    ]
